repos:
    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: poetry run isort -c blackboxopt/
          language: system
          always_run: true
          pass_filenames: false
          
        - id: pylint
          name: pylint
          entry: poetry run pylint blackboxopt/ --max-line-length=120 --ignore=tests --fail-under=7
          language: system
          always_run: true
          pass_filenames: false

        - id: pytest
          name: pytest
          entry: poetry run pytest -W ignore tests/ --cov blacboxopt/
          language: system
          always_run: true
          pass_filenames: false

        - id: coverage
          name: coverage
          entry: poetry run coverage report --fail-under=0 # fail-under=90
          language: system
          always_run: true
          pass_filenames: false
